SGHMC_Final_Report.pdf: SGHMC_Final_Report.tex posterior_samples pima simulated
	pdflatex SGHMC_Final_Report.tex

posterior_samples: 
	python posterior_samples.py

pima:
	python logistic_regression_pima.py

simulated:
	python logistic_regression_simulated.py